// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAY_TWzUmO-0YWjnZYmLyn4GkkfilENFjI',
    appId: '1:1035069107999:web:0b7fc22111b3e512088a2a',
    messagingSenderId: '1035069107999',
    projectId: 'flutter-remanente',
    authDomain: 'flutter-remanente.firebaseapp.com',
    storageBucket: 'flutter-remanente.firebasestorage.app',
    measurementId: 'G-N77LM1VQGQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6AKod62M9lMpIlP6XgH917HbMrWCLI_o',
    appId: '1:1035069107999:android:55470a5d50b1f80b088a2a',
    messagingSenderId: '1035069107999',
    projectId: 'flutter-remanente',
    storageBucket: 'flutter-remanente.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeu1k4rcPHgcECMDxPKkHZ99vGkUx5uCo',
    appId: '1:1035069107999:ios:ab98bb6619d6b35d088a2a',
    messagingSenderId: '1035069107999',
    projectId: 'flutter-remanente',
    storageBucket: 'flutter-remanente.firebasestorage.app',
    iosBundleId: 'com.example.flutterRemanente',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeu1k4rcPHgcECMDxPKkHZ99vGkUx5uCo',
    appId: '1:1035069107999:ios:ab98bb6619d6b35d088a2a',
    messagingSenderId: '1035069107999',
    projectId: 'flutter-remanente',
    storageBucket: 'flutter-remanente.firebasestorage.app',
    iosBundleId: 'com.example.flutterRemanente',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAY_TWzUmO-0YWjnZYmLyn4GkkfilENFjI',
    appId: '1:1035069107999:web:989d0e016194d2e3088a2a',
    messagingSenderId: '1035069107999',
    projectId: 'flutter-remanente',
    authDomain: 'flutter-remanente.firebaseapp.com',
    storageBucket: 'flutter-remanente.firebasestorage.app',
    measurementId: 'G-4385E070WF',
  );
}
